server:
  port: 9098


#spring:
#  security:
#    user:
#      name: admin
spring:
  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://127.0.0.1:3306/fanfan_cms?characterEncoding=UTF8

mybatis:
  type-aliases-package: cn.fanfannet.admin.entity
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


#      password: 123456